CREATE OR REPLACE FUNCTION isTime(_ TEXT)
RETURNS boolean
AS
$$
DECLARE
  d time;
BEGIN
  IF _ IS NULL THEN
    RETURN false;
  END IF;
  d = _::time;
  RETURN true;
  EXCEPTION WHEN others THEN
    RETURN FALSE;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
